{% set name = "lark" %}
{% set version = "1.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lark-{{ version }}.tar.gz
  sha256: 7ef424db57f59c1ffd6f0d4c2b705119927f566b68c0fe1942dddcc0e44391a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - regex
    - pip
    - python >=3.6
  run:
    - atomicwrites
    - js2py
    - python >=3.6
    - regex

test:
  imports:
    - lark
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lark-parser/lark
  summary: a modern parsing library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
